[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"


[lib]
name = "advent"
path = "src/lib/mod.rs"

[[bin]]
name = "aoc"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
