# List available commands.
list:
  @just -l

# Bootstrap a new puzzle. Expects DATE to be an int from 1 to 25.
new DATE:
  @curl "https://adventofcode.com/2024/day/{{DATE}}/input" \
    -H "cookie: session=${SESSION}" \
    --compressed \
    -o inputs/day-{{DATE}}.txt
  @echo {{ DATE }} | cakemix -o solutions template

# Run solution for specified date.
run DATE:
  @go run . {{DATE}}

# Run solution using test data.
test DATE:
  @TEST=true just run {{DATE}} 
