list:
  @just -l

# Evaluate select part of solution. Must be in solutions/day-n/ dir.
run PART="1" TEST="false" DEBUG="false":
  @DEBUG={{DEBUG}} TEST={{TEST}} nix-instantiate --eval --expr 'import {{invocation_directory()}}/part_{{PART}}.nix'

# Same as [run] but with debug enabled.
debug PART="1" TEST="false":
  @cd {{invocation_directory()}} && just run {{PART}} {{TEST}} true

# Same as [run] but with test and debug enabled.
test PART="1":
  @cd {{invocation_directory()}} && just run {{PART}} true true
